provider: mysql
major-version: 3
docker: true
makeTemplate: bridged
pulumiConvert: 1
registryDocs: true
plugins:
  - name: terraform
    version: "1.0.16"
    kind: converter
checkUpstreamUpgrade: false