provider: mysql
major-version: 3
docker: true
makeTemplate: bridged
pulumiConvert: 1
registryDocs: true
checkUpstreamUpgrade: false
esc:
    enabled: true
    environment: imports/github-secrets # No repo-specific secrets.
