// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
	"github.com/pulumi/pulumi/sdk/go/pulumi/config"
)

func GetAuthenticationPlugin(ctx *pulumi.Context) string {
	return config.Get(ctx, "mysql:authenticationPlugin")
}

func GetEndpoint(ctx *pulumi.Context) string {
	return config.Get(ctx, "mysql:endpoint")
}

func GetMaxConnLifetimeSec(ctx *pulumi.Context) int {
	return config.GetInt(ctx, "mysql:maxConnLifetimeSec")
}

func GetMaxOpenConns(ctx *pulumi.Context) int {
	return config.GetInt(ctx, "mysql:maxOpenConns")
}

func GetPassword(ctx *pulumi.Context) string {
	return config.Get(ctx, "mysql:password")
}

func GetProxy(ctx *pulumi.Context) string {
	return config.Get(ctx, "mysql:proxy")
}

func GetTls(ctx *pulumi.Context) string {
	return config.Get(ctx, "mysql:tls")
}

func GetUsername(ctx *pulumi.Context) string {
	return config.Get(ctx, "mysql:username")
}
