// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi-mysql/sdk/v3/go/mysql/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

func GetAuthenticationPlugin(ctx *pulumi.Context) string {
	return config.Get(ctx, "mysql:authenticationPlugin")
}
func GetEndpoint(ctx *pulumi.Context) string {
	return config.Get(ctx, "mysql:endpoint")
}
func GetMaxConnLifetimeSec(ctx *pulumi.Context) int {
	return config.GetInt(ctx, "mysql:maxConnLifetimeSec")
}
func GetMaxOpenConns(ctx *pulumi.Context) int {
	return config.GetInt(ctx, "mysql:maxOpenConns")
}
func GetPassword(ctx *pulumi.Context) string {
	return config.Get(ctx, "mysql:password")
}
func GetProxy(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "mysql:proxy")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault(nil, nil, "ALL_PROXY", "all_proxy"); d != nil {
		value = d.(string)
	}
	return value
}
func GetTls(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "mysql:tls")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault("false", nil, "MYSQL_TLS_CONFIG"); d != nil {
		value = d.(string)
	}
	return value
}
func GetUsername(ctx *pulumi.Context) string {
	return config.Get(ctx, "mysql:username")
}
