// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

// nolint: lll
package mysql

import (
	"github.com/pulumi/pulumi/sdk/go/pulumi"
)

func init() {
	pulumi.RegisterPackage(pulumi.PackageInfo{Name: "mysql", Version: "1.5.0+dirty"})
}
