// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.mysql;

import com.pulumi.core.internal.Codegen;
import java.lang.Integer;
import java.lang.String;
import java.util.Optional;

public final class Config {

    private static final com.pulumi.Config config = com.pulumi.Config.of("mysql");
    public Optional<String> authenticationPlugin() {
        return Codegen.stringProp("authenticationPlugin").config(config).get();
    }
    public String endpoint() {
        return Codegen.stringProp("endpoint").config(config).require();
    }
    public Optional<Integer> maxConnLifetimeSec() {
        return Codegen.integerProp("maxConnLifetimeSec").config(config).get();
    }
    public Optional<Integer> maxOpenConns() {
        return Codegen.integerProp("maxOpenConns").config(config).get();
    }
    public Optional<String> password() {
        return Codegen.stringProp("password").config(config).get();
    }
    public Optional<String> proxy() {
        return Codegen.stringProp("proxy").config(config).env("ALL_PROXY", "all_proxy").get();
    }
    public Optional<String> tls() {
        return Codegen.stringProp("tls").config(config).env("MYSQL_TLS_CONFIG").def("false").get();
    }
    public String username() {
        return Codegen.stringProp("username").config(config).require();
    }
}
