# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

authenticationPlugin: Optional[str]

endpoint: Optional[str]

maxConnLifetimeSec: Optional[int]

maxOpenConns: Optional[int]

password: Optional[str]

proxy: Optional[str]

tls: str

username: Optional[str]

