# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

import types

__config__ = pulumi.Config('mysql')


class _ExportableConfig(types.ModuleType):
    @property
    def authentication_plugin(self) -> Optional[str]:
        return __config__.get('authenticationPlugin')

    @property
    def endpoint(self) -> Optional[str]:
        return __config__.get('endpoint')

    @property
    def max_conn_lifetime_sec(self) -> Optional[int]:
        return __config__.get_int('maxConnLifetimeSec')

    @property
    def max_open_conns(self) -> Optional[int]:
        return __config__.get_int('maxOpenConns')

    @property
    def password(self) -> Optional[str]:
        return __config__.get('password')

    @property
    def proxy(self) -> Optional[str]:
        return __config__.get('proxy') or _utilities.get_env('ALL_PROXY', 'all_proxy')

    @property
    def tls(self) -> str:
        return __config__.get('tls') or (_utilities.get_env('MYSQL_TLS_CONFIG') or 'false')

    @property
    def username(self) -> Optional[str]:
        return __config__.get('username')

