# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import json
import warnings
import pulumi
import pulumi.runtime
from .. import utilities, tables

__config__ = pulumi.Config('mysql')

endpoint = __config__.get('endpoint')

password = __config__.get('password')

tls = __config__.get('tls')

username = __config__.get('username')

