# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

_SNAKE_TO_CAMEL_CASE_TABLE = {
    "auth_plugin": "authPlugin",
    "default_character_set": "defaultCharacterSet",
    "default_collation": "defaultCollation",
    "encrypted_password": "encryptedPassword",
    "key_fingerprint": "keyFingerprint",
    "pgp_key": "pgpKey",
    "plaintext_password": "plaintextPassword",
    "tls_option": "tlsOption",
}

_CAMEL_TO_SNAKE_CASE_TABLE = {
    "authPlugin": "auth_plugin",
    "defaultCharacterSet": "default_character_set",
    "defaultCollation": "default_collation",
    "encryptedPassword": "encrypted_password",
    "keyFingerprint": "key_fingerprint",
    "pgpKey": "pgp_key",
    "plaintextPassword": "plaintext_password",
    "tlsOption": "tls_option",
}
