// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { DatabaseArgs, DatabaseState } from "./database";
export type Database = import("./database").Database;
export const Database: typeof import("./database").Database = null as any;
utilities.lazyLoad(exports, ["Database"], () => require("./database"));

export { GrantArgs, GrantState } from "./grant";
export type Grant = import("./grant").Grant;
export const Grant: typeof import("./grant").Grant = null as any;
utilities.lazyLoad(exports, ["Grant"], () => require("./grant"));

export * from "./provider";
import { Provider } from "./provider";

export { RoleArgs, RoleState } from "./role";
export type Role = import("./role").Role;
export const Role: typeof import("./role").Role = null as any;
utilities.lazyLoad(exports, ["Role"], () => require("./role"));

export { UserArgs, UserState } from "./user";
export type User = import("./user").User;
export const User: typeof import("./user").User = null as any;
utilities.lazyLoad(exports, ["User"], () => require("./user"));

export { UserPasswordArgs, UserPasswordState } from "./userPassword";
export type UserPassword = import("./userPassword").UserPassword;
export const UserPassword: typeof import("./userPassword").UserPassword = null as any;
utilities.lazyLoad(exports, ["UserPassword"], () => require("./userPassword"));


// Export sub-modules:
import * as config from "./config";

export {
    config,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "mysql:index/database:Database":
                return new Database(name, <any>undefined, { urn })
            case "mysql:index/grant:Grant":
                return new Grant(name, <any>undefined, { urn })
            case "mysql:index/role:Role":
                return new Role(name, <any>undefined, { urn })
            case "mysql:index/user:User":
                return new User(name, <any>undefined, { urn })
            case "mysql:index/userPassword:UserPassword":
                return new UserPassword(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("mysql", "index/database", _module)
pulumi.runtime.registerResourceModule("mysql", "index/grant", _module)
pulumi.runtime.registerResourceModule("mysql", "index/role", _module)
pulumi.runtime.registerResourceModule("mysql", "index/user", _module)
pulumi.runtime.registerResourceModule("mysql", "index/userPassword", _module)
pulumi.runtime.registerResourcePackage("mysql", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:mysql") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
