// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * The provider type for the mysql package. By default, resources use package-wide configuration
 * settings, however an explicit `Provider` instance may be created and passed during resource
 * construction to achieve fine-grained programmatic control over provider settings. See the
 * [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
 */
export class Provider extends pulumi.ProviderResource {
    /** @internal */
    public static readonly __pulumiType = 'mysql';

    /**
     * Returns true if the given object is an instance of Provider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Provider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === "pulumi:providers:" + Provider.__pulumiType;
    }

    public readonly authenticationPlugin!: pulumi.Output<string | undefined>;
    public readonly endpoint!: pulumi.Output<string>;
    public readonly password!: pulumi.Output<string | undefined>;
    public readonly proxy!: pulumi.Output<string | undefined>;
    public readonly tls!: pulumi.Output<string | undefined>;
    public readonly username!: pulumi.Output<string>;

    /**
     * Create a Provider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ProviderArgs, opts?: pulumi.ResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        {
            if ((!args || args.endpoint === undefined) && !opts.urn) {
                throw new Error("Missing required property 'endpoint'");
            }
            if ((!args || args.username === undefined) && !opts.urn) {
                throw new Error("Missing required property 'username'");
            }
            resourceInputs["authenticationPlugin"] = args ? args.authenticationPlugin : undefined;
            resourceInputs["endpoint"] = args ? args.endpoint : undefined;
            resourceInputs["maxConnLifetimeSec"] = pulumi.output(args ? args.maxConnLifetimeSec : undefined).apply(JSON.stringify);
            resourceInputs["maxOpenConns"] = pulumi.output(args ? args.maxOpenConns : undefined).apply(JSON.stringify);
            resourceInputs["password"] = args ? args.password : undefined;
            resourceInputs["proxy"] = (args ? args.proxy : undefined) ?? utilities.getEnv("ALL_PROXY", "all_proxy");
            resourceInputs["tls"] = (args ? args.tls : undefined) ?? (utilities.getEnv("MYSQL_TLS_CONFIG") || "false");
            resourceInputs["username"] = args ? args.username : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Provider.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Provider resource.
 */
export interface ProviderArgs {
    authenticationPlugin?: pulumi.Input<string>;
    endpoint: pulumi.Input<string>;
    maxConnLifetimeSec?: pulumi.Input<number>;
    maxOpenConns?: pulumi.Input<number>;
    password?: pulumi.Input<string>;
    proxy?: pulumi.Input<string>;
    tls?: pulumi.Input<string>;
    username: pulumi.Input<string>;
}
